# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

kind: Service
apiVersion: v1
metadata:
  name: mcm-apiserver
  namespace: multicloud-system
spec:
  selector:
    app: mcm-apiserver
  ports:
  - name: secure
    protocol: TCP
    port: 443
    targetPort: 443

---

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.mcm.ibm.com
spec:
  group: mcm.ibm.com
  version: v1alpha1
  service:
    namespace: multicloud-system
    name: mcm-apiserver
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 10000
  versionPriority: 20

---

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  version: v1alpha1
  service:
    namespace: multicloud-system
    name: mcm-apiserver
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 10000
  versionPriority: 20

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcm-apiserver
  namespace: multicloud-system
  labels:
    app: mcm-apiserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcm-apiserver
  template:
    metadata:
      labels:
        app: mcm-apiserver
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: mcm-apiserver
        image: github.ibm.com/IBMPrivateCloud/multicloud-operators-foundation/cmd/mcm-apiserver
        imagePullPolicy: IfNotPresent
        env:
        - name: MYHUBNAME
          value: hub0
        args:
          - "/mcm-apiserver"
          - "--mongo-host=mongo-0.mongo"
          - "--mongo-database=mcm"
          - "--mongo-replicaset=rs0"
          - "--etcd-servers=etcd-0.etcd:2379,etcd-1.etcd:2379,etcd-2.etcd:2379"
          - "--enable-admission-plugins=HCMUserIdentity,KlusterletCA,NamespaceLifecycle"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 2
