apiVersion: v1
kind: ConfigMap
metadata:
  name: mcm-serviceregistry-coredns
  namespace: multicloud-endpoint
  labels:
    app: mcm-serviceregistry
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        reload
        cache 30
        file /etc/coredns/svcregistry.db mcm.svc {
          reload 5s
        }
    }
  svcregistry.db: |
    mcm.svc.    IN    SOA    mcm-svcreg-dns.multicloud-endpoint.svc.cluster.local. hostmaster.cluster.local. 1563330020 7200 1800 86400 30

---

apiVersion: v1
kind: Service
metadata:
  name: mcm-svcreg-dns
  namespace: multicloud-endpoint
  labels:
    app: mcm-serviceregistry
spec:
  selector:
    app: mcm-serviceregistry
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-serviceregistry-coredns
  namespace: multicloud-endpoint
  labels:
    app: mcm-serviceregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcm-serviceregistry
  template:
    metadata:
      labels:
        app: mcm-serviceregistry
    spec:
      containers:
      - name: mcm-serviceregistry-coredns
        image: k8s.gcr.io/coredns:1.3.1
        imagePullPolicy: IfNotPresent
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: mcm-serviceregistry-coredns
            items:
            - key: Corefile
              path: Corefile
            - key: svcregistry.db
              path: svcregistry.db
