# This workset create an configmap in clusters with label cloud: k8s
apiVersion: mcm.ibm.com/v1alpha1
kind: WorkSet
metadata:
  name: workset-create
spec:
  clusterSelector:
    matchLabels:
      cloud: k8s
  template:
    spec:
      type: Action
      actionType: Create
      kube:
        resource: configmap
        namespace: default
        template:
          apiVersion: v1
          data:
            redis-config: |
              maxmemory 2mb
              maxmemory-policy allkeys-lru
          kind: ConfigMap
          metadata:
            name: example-redis-config
