resources:
- ../../dev/klusterlet/

images:
- name: ko://github.com/open-cluster-management/multicloud-operators-foundation/cmd/acm-agent
  newName: quay.io/open-cluster-management/multicloud-manager
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
